# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

target 'RNNativeEmberLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  source = 'https://github.com/EnasAhmedZaki/EMBERPodFramework.git'
  # Pods for EMBERPodFramework
  pod 'EMBERPodFramework'

#  pod 'React', :subspecs => ['Core'], :path => '../node_modules/react-native'
end
